### ISSUE TITLE
Table-inside-table on user page

### ISSUE THREAD

**Issue by svivian** [NoahY/q2a-badges#6]
On the user pages the badge table appears inside another table. It looks OK on the default theme but it looks bad on my theme:

![badges](http://i.imgur.com/atHDd.jpg)

Is it possible to put it in its own table, without the wrapper table? And add your own CSS class to the table so we can style it differently if need be?

**Comment by NoahY** [comment]
The problem is it's a form (with an optional text box for receiving 
email notifications.  Forms are all in tables in the theme system, 
unless they don't have form fields.  So, I think it's probably best to 
just give the table a css class and work around the problem.  Hopefully 
that is possible; I've given it the class of badge-table.
